-- 2026-10-04：来源名统一成「名字（国家 · 类型）」（读者在每条内容上看得到），并改正核对出的国家标签（标签也给模型看）。
-- seed.ts 不改已有来源，所以线上要跑这一份。只改名字或标签不同的行，可重复运行：第一次打印 renamed 72，再运行打印 renamed 0。
WITH changed AS (
UPDATE sources s SET name = v.name, tags = v.tags, updated_at = now()
FROM (VALUES
  ('rss-fsr', 'FSR Magazine（美国 · 餐饮媒体）', ARRAY['美国', '媒体']::text[]),
  ('rss-totalfood', 'Total Food Service（美国 · 餐饮媒体）', ARRAY['美国', '媒体']::text[]),
  ('web-qsrmedia-asia', 'QSR Media Asia（亚洲 · 快餐与连锁媒体）', ARRAY['亚洲', '媒体']::text[]),
  ('web-canyin88-zhuanlan', '红餐网 · 专栏（中国 · 餐饮媒体）', ARRAY['中国', '媒体']::text[]),
  ('rss-barista-magazine', 'Barista Magazine（美国 · 咖啡媒体）', ARRAY['美国', '媒体']::text[]),
  ('rss-qsrmedia-au', 'QSR Media（澳大利亚、英国 · 快餐与连锁媒体）', ARRAY['澳大利亚', '英国', '媒体']::text[]),
  ('rss-hospitality-au', 'Hospitality（澳大利亚 · 餐饮媒体）', ARRAY['澳大利亚', '媒体']::text[]),
  ('rss-ristorazione-italiana', 'Ristorazione Italiana Magazine（意大利 · 餐饮媒体）', ARRAY['意大利', '媒体']::text[]),
  ('rss-foodrink', 'フードリンクニュース（日本 · 餐饮媒体）', ARRAY['日本', '媒体']::text[]),
  ('web-canyin88-zixun', '红餐网 · 资讯（中国 · 餐饮媒体）', ARRAY['中国', '媒体']::text[]),
  ('rss-ahresp', 'AHRESP（葡萄牙 · 餐饮协会）', ARRAY['葡萄牙', '协会']::text[]),
  ('rss-bargiornale', 'Bargiornale（意大利 · 餐饮媒体）', ARRAY['意大利', '媒体']::text[]),
  ('rss-fipe', 'FIPE（意大利 · 餐饮协会）', ARRAY['意大利', '协会']::text[]),
  ('rss-fresh-cup', 'Fresh Cup（美国 · 咖啡媒体）', ARRAY['美国', '媒体']::text[]),
  ('rss-gast-at', 'Gast（奥地利 · 餐饮媒体）', ARRAY['奥地利', '媒体']::text[]),
  ('rss-hospitality-ireland', 'Hospitality Ireland（爱尔兰 · 餐饮媒体）', ARRAY['爱尔兰', '媒体']::text[]),
  ('rss-marginedge', 'MarginEdge（美国 · 餐厅财务软件商）', ARRAY['美国', '平台']::text[]),
  ('pod-hospitality-talks', 'Hospitality Talks（英国 · 餐饮咨询公司的播客）', ARRAY['英国', '播客']::text[]),
  ('pod-restaurant-reset', 'Restaurant Reset（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-a-la-carte-par-fooddy-le-podcast-qui-par', 'A LA CARTE par Fooddy（法国 · 播客）', ARRAY['法国', '播客']::text[]),
  ('pod-jp-inshoku-ai-radio', '飲食店のAI活用ラジオ（日本 · 餐厅老板的播客）', ARRAY['日本', '播客']::text[]),
  ('pod-horeca-channel-italia', 'HORECA CHANNEL ITALIA（意大利 · 播客）', ARRAY['意大利', '播客']::text[]),
  ('pod-horeca-audio-news-le-pillole-quotidiane', 'HORECA AUDIO NEWS（意大利 · 播客）', ARRAY['意大利', '播客']::text[]),
  ('pod-tw-renren-canyin', '人人品牌 · 餐飲經營筆記（中国台湾 · 播客）', ARRAY['中国台湾', '播客']::text[]),
  ('pod-the-restaurant-technology-guys-podcast-b', 'The Restaurant Technology Guys Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-strategic-business-growth-systems-restau', 'Strategic Business Growth Systems（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-marketing-morsels-for-restaurants', 'Marketing Morsels for Restaurants（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-strategy', 'Restaurant Strategy（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-total-food-service', 'Total Food Service（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-the-bar-business-podcast-bar-pub-owner-p', 'The Bar Business Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-qsr-uncut', 'QSR Uncut（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-the-build-restuarant-201', 'The Build: Restuarant 201（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-der-gastro-podcast', 'DER GASTRO PODCAST（德国 · 播客）', ARRAY['德国', '播客']::text[]),
  ('pod-fettgespraeche', 'Fettgespräche（德国 · 播客）', ARRAY['德国', '播客']::text[]),
  ('pod-the-ristoratori', 'The Ristoratori（意大利 · 播客）', ARRAY['意大利', '播客']::text[]),
  ('pod-jp-omise-radio-smaregi', 'お店ラジオ2（日本 · 播客）', ARRAY['日本', '播客']::text[]),
  ('pod-restaurant-wealth', 'Restaurant Wealth Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-finance-podcast', 'The Restaurant Finance Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-growth-accelerator', 'Restaurant Growth Accelerator（加拿大 · 播客）', ARRAY['加拿大', '播客']::text[]),
  ('prt-141863', 'ExpreTech（日本 · 服务商新闻稿）', ARRAY['日本', '平台']::text[]),
  ('rss-foodnews-kr', '식품저널（韩国 · 食品与餐饮媒体）', ARRAY['韩国', '媒体']::text[]),
  ('blog-eats365', 'Eats365 博客（中国香港 · 收银系统商）', ARRAY['中国香港', '服务商']::text[]),
  ('rss-hospitality-nz', 'Hospitality Business（新西兰 · 餐饮媒体）', ARRAY['新西兰', '媒体']::text[]),
  ('rss-ristorando', 'Ristorando（意大利 · 餐饮媒体）', ARRAY['意大利', '媒体']::text[]),
  ('pod-valor-coffee', 'Valor Coffee Podcast（美国 · 咖啡店老板的播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-prosperity-formula', 'The Restaurant Prosperity Formula（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('rss-petpooja', 'Petpooja 博客（印度 · 收银系统商）', ARRAY['印度', '媒体']::text[]),
  ('pod-panaderia-facil', 'Panadería fácil para emprendedores（阿根廷 · 面包店创业播客）', ARRAY['阿根廷', '播客']::text[]),
  ('pod-tw-kaidian-zhejianshi', '開店這件事（中国台湾 · 小店老板的播客）', ARRAY['中国台湾', '播客']::text[]),
  ('pod-full-comp', 'FULL COMP（美国 · 餐厅老板的播客）', ARRAY['美国', '播客']::text[]),
  ('pod-build-a-better-restaurant', 'Build A Better Restaurant（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-rockstars', 'Restaurant Rockstars Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-marketing-secrets', 'Restaurant Marketing Secrets（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-great-work-for-restaurants', 'Great Work for Restaurants（加拿大 · 播客）', ARRAY['加拿大', '播客']::text[]),
  ('pod-coffee-experts-club', 'The Coffee Experts Club Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-pulling-shots', 'Pulling Shots（美国 · 咖啡店老板的播客）', ARRAY['美国', '播客']::text[]),
  ('pod-keys-to-the-shop', 'Keys To The Shop（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-food-business-blueprint', 'The Food Business Blueprint Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-your-life-and-restaurant', 'Your Life and Restaurant（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-fr-passe-moi-le-sel', 'Passe moi le sel（法国 · 播客）', ARRAY['法国', '播客']::text[]),
  ('pod-kr-baemin-owner-talk', '사장님 라이브 토크（韩国 · 外卖平台 Baemin 的播客）', ARRAY['韩国', '播客']::text[]),
  ('pod-entre-hosteleros', 'ENTRE HOSTELEROS（西班牙 · 播客）', ARRAY['西班牙', '播客']::text[]),
  ('pod-say86-hospitality', 'say86 Hospitality Podcast（英国 · 播客）', ARRAY['英国', '播客']::text[]),
  ('pod-elevated-hospitality', 'The Elevated Hospitality Podcast（美国 · 播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-hero', 'Restaurant Hero（德国 · 播客）', ARRAY['德国', '播客']::text[]),
  ('pod-restaurant-deal-making-exposed-with-patr', 'Restaurant Deal Making EXPOSED!（美国 · 餐厅买卖经纪人的播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-coach', 'The Restaurant Coach Podcast（美国 · 餐厅顾问的播客）', ARRAY['美国', '播客']::text[]),
  ('pod-restaurant-technology-podcast', 'Restaurant Technology Podcast（美国 · Cali BBQ 老板的播客）', ARRAY['美国', '播客']::text[]),
  ('web-gnavi-pro-tokushu', 'ぐるなび通信 · 特集（日本 · 餐饮信息平台）', ARRAY['日本', '媒体']::text[]),
  ('web-gnavi-pro-hanjo', 'ぐるなび通信 · 今、繁盛している店（日本 · 餐饮信息平台）', ARRAY['日本', '媒体']::text[]),
  ('rss-tenpo-biz-column', '店舗流通ネット（日本 · 店铺租赁服务商）', ARRAY['日本', '服务商']::text[]),
  ('web-goomer-blog', 'Goomer 博客（巴西 · 点餐系统商）', ARRAY['巴西', '服务商']::text[])
) AS v(id, name, tags)
WHERE s.id = v.id AND (s.name IS DISTINCT FROM v.name OR s.tags IS DISTINCT FROM v.tags)
RETURNING s.id
)
SELECT 'renamed ' || count(*) FROM changed;
